package View;
import Database.CustomerConnection;
import Database.ReservationConnection;
import Models.Customer;
/**
 *
 * @author Charlie
 */
public class AvailableRoomsGUI extends javax.swing.JPanel {
    
    /**
     * Creates new form AvailableRoomsGUI
     */
     GUI gui;
     CustomerGUI customergui;
      CustomerConnection customerconnection = new CustomerConnection();
      ReservationConnection reservationConnection = new ReservationConnection();
     
     
    public AvailableRoomsGUI(GUI gui) {
        
        initComponents();
        this.gui = gui;
        customerIDTF.setText(String.valueOf(customerconnection.getNewestCustomerID()));
        numberofRoomsTF.setText(String.valueOf(reservationConnection.getNewestReservation().getNumberOfRooms()));
        totalPriceTF.setText(String.valueOf(reservationConnection.getNewestReservation().getTotalPrice()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fifloorButton = new javax.swing.JButton();
        fofloorButton = new javax.swing.JButton();
        tfloorButton = new javax.swing.JButton();
        sfloorButton = new javax.swing.JButton();
        ffloorButton = new javax.swing.JButton();
        nextButtonAR = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        numberofRoomsTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        totalPriceTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        customerIDTF = new javax.swing.JTextField();

        fifloorButton.setText("5 Floor");
        fifloorButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                fifloorButtonMouseReleased(evt);
            }
        });

        fofloorButton.setText("4 Floor");
        fofloorButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                fofloorButtonMouseReleased(evt);
            }
        });

        tfloorButton.setText("3 Floor");
        tfloorButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tfloorButtonMouseReleased(evt);
            }
        });

        sfloorButton.setText("2 Floor");
        sfloorButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                sfloorButtonMouseReleased(evt);
            }
        });

        ffloorButton.setText("1 Floor");
        ffloorButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ffloorButtonMouseReleased(evt);
            }
        });

        nextButtonAR.setText("Next");
        nextButtonAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                nextButtonARMouseReleased(evt);
            }
        });

        jLabel1.setText("Number of booked rooms:");

        jLabel2.setText("Total Price:");

        jLabel3.setText("CustomerID :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(457, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ffloorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(fofloorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fifloorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfloorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sfloorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalPriceTF, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(numberofRoomsTF, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(customerIDTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(152, 152, 152)
                        .addComponent(nextButtonAR, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(211, 211, 211))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(206, Short.MAX_VALUE)
                .addComponent(fifloorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(fofloorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(tfloorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(sfloorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(ffloorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numberofRoomsTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalPriceTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(85, 85, 85))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(nextButtonAR)
                        .addGap(95, 95, 95))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ffloorButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ffloorButtonMouseReleased
        FirstFloorGUI firstfloor = new FirstFloorGUI(gui);
  
            gui.jPanel2Main.removeAll();
            gui.jPanel2Main.add(firstfloor);
            gui.setVisible(true);
         
    }//GEN-LAST:event_ffloorButtonMouseReleased

    private void sfloorButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sfloorButtonMouseReleased
        SecondFloorGUI secondfloor = new SecondFloorGUI(gui);
  
            gui.jPanel2Main.removeAll();
            gui.jPanel2Main.add(secondfloor);
            gui.setVisible(true);
    }//GEN-LAST:event_sfloorButtonMouseReleased

    private void tfloorButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfloorButtonMouseReleased
       ThirdFloorGUI thirdfloor = new ThirdFloorGUI(gui);
  
            gui.jPanel2Main.removeAll();
            gui.jPanel2Main.add(thirdfloor);
            gui.setVisible(true);
    }//GEN-LAST:event_tfloorButtonMouseReleased

    private void fofloorButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fofloorButtonMouseReleased
        FourthFloorGUI fourthfloor = new FourthFloorGUI(gui);
  
            gui.jPanel2Main.removeAll();
            gui.jPanel2Main.add(fourthfloor);
            gui.setVisible(true);
    }//GEN-LAST:event_fofloorButtonMouseReleased

    private void fifloorButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fifloorButtonMouseReleased
        FifthFloorGUI fifthfloor = new FifthFloorGUI(gui);
  
            gui.jPanel2Main.removeAll();
            gui.jPanel2Main.add(fifthfloor);
            gui.setVisible(true);
    }//GEN-LAST:event_fifloorButtonMouseReleased

    private void nextButtonARMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButtonARMouseReleased
        PaymentGUI payment = new PaymentGUI(gui);    
        
            gui.jPanel2Main.removeAll();
            gui.jPanel2Main.repaint();
            gui.jPanel2Main.add(payment);
            gui.jPanel2Main.repaint();
            gui.setVisible(true);
    }//GEN-LAST:event_nextButtonARMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField customerIDTF;
    private javax.swing.JButton ffloorButton;
    private javax.swing.JButton fifloorButton;
    private javax.swing.JButton fofloorButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton nextButtonAR;
    public javax.swing.JTextField numberofRoomsTF;
    private javax.swing.JButton sfloorButton;
    private javax.swing.JButton tfloorButton;
    public javax.swing.JTextField totalPriceTF;
    // End of variables declaration//GEN-END:variables
}
