package View;

import Database.CustomerConnection;
import Database.ReservationConnection;
import Database.RoomConnection;
import Models.Reservation;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;

/**
 *
 * @author Charlie
 */
public class FifthFloorGUI extends javax.swing.JPanel {
    DefaultListModel dlm=new DefaultListModel();
    private static ArrayList<String> clickButton=new ArrayList<String>();
    List<Integer> priceList = new ArrayList<Integer>();
    RoomConnection roomConnection = new RoomConnection();
    CustomerConnection customerconnection = new CustomerConnection();
    ReservationConnection reservationconnection = new ReservationConnection();
    GUI gui;
    /**
     * Creates new form FifthFloorGUI
     */
    public FifthFloorGUI(GUI gui) {
        initComponents();
        this.gui=gui;
        customerIDTF.setText(String.valueOf(customerconnection.getNewestCustomerID()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Fi01jButton = new javax.swing.JButton();
        Fi02jButton = new javax.swing.JButton();
        Fi03jButton = new javax.swing.JButton();
        Fi04jButton = new javax.swing.JButton();
        Fi05jButton = new javax.swing.JButton();
        Fi06jButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        okButton5 = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        priceOfRoomsjList = new javax.swing.JList();
        numOfRoomTF = new javax.swing.JTextField();
        totalTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        customerIDTF = new javax.swing.JTextField();

        Fi01jButton.setText("Fif1");
        Fi01jButton.setToolTipText("Room for 2 Persons");
        Fi01jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Fi01jButtonMouseReleased(evt);
            }
        });

        Fi02jButton.setText("Fif2");
        Fi02jButton.setToolTipText("Room for 1 Person");
        Fi02jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Fi02jButtonMouseReleased(evt);
            }
        });

        Fi03jButton.setText("Fif3");
        Fi03jButton.setToolTipText("Luxus Room for 2 Persons");
        Fi03jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Fi03jButtonMouseReleased(evt);
            }
        });

        Fi04jButton.setText("Fif4");
        Fi04jButton.setToolTipText("Room for 2 Persons");
        Fi04jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Fi04jButtonMouseReleased(evt);
            }
        });

        Fi05jButton.setText("Fif5");
        Fi05jButton.setToolTipText("Room for 1 Person");
        Fi05jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Fi05jButtonMouseReleased(evt);
            }
        });

        Fi06jButton.setText("Fif6");
        Fi06jButton.setToolTipText("Family Room");
        Fi06jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Fi06jButtonMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Fi02jButton, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(Fi01jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Fi03jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(Fi06jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Fi04jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Fi05jButton, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Fi04jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Fi02jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Fi03jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 90, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Fi01jButton, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                    .addComponent(Fi05jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Fi06jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        backButton.setText("Back");
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                backButtonMouseReleased(evt);
            }
        });

        okButton5.setText("OK");
        okButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                okButton5MouseReleased(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cancelButtonMouseReleased(evt);
            }
        });

        jScrollPane1.setViewportView(priceOfRoomsjList);

        jLabel1.setText("Price for each room :");

        jLabel2.setText("Number of rooms :");

        jLabel3.setText("Total :");

        jLabel4.setText("CustomerID : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(208, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(numOfRoomTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(customerIDTF, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(totalTF, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel4))
                        .addGap(87, 87, 87)
                        .addComponent(okButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(221, 221, 221))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(backButton)
                            .addComponent(okButton5)
                            .addComponent(cancelButton))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(customerIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numOfRoomTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseReleased
         AvailableRoomsGUI availableRooms=new AvailableRoomsGUI(gui);
  
            
            gui.jPanel2Main.removeAll();
            gui.jPanel2Main.repaint();
            gui.jPanel2Main.add(availableRooms);
            gui.jPanel2Main.repaint();
            gui.setVisible(true);
            clickButton.clear();
    }//GEN-LAST:event_backButtonMouseReleased

    private void okButton5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okButton5MouseReleased
        int fn = Integer.parseInt(customerIDTF.getText());
        int num = Integer.parseInt(numOfRoomTF.getText());
        int total = Integer.parseInt(totalTF.getText());
        
        
        Reservation reservation = new Reservation(fn,num,total);
        try {
            reservationconnection.createReservation(reservation);
        } catch (SQLException ex) {
            Logger.getLogger(FirstFloorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
            AvailableRoomsGUI availableRooms=new AvailableRoomsGUI(gui);
            
            gui.jPanel2Main.removeAll();
            gui.jPanel2Main.add(availableRooms);
            gui.jPanel2Main.repaint();
            gui.setVisible(true);
    }//GEN-LAST:event_okButton5MouseReleased

    private void Fi01jButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Fi01jButtonMouseReleased
        Fi01jButton.setBackground(Color.blue);
        clickButton.add("Fi01");
        int roomNr=26;
        
      // List<String> priceList = new ArrayList<String>();
            
        try {
            priceList.add(roomConnection.searchRoomID(roomNr).getRoomPrice());
        } catch (SQLException ex) {
            Logger.getLogger(FirstFloorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        dlm.clear();
      
        for(int i = 0; i < priceList.size(); i++) {
            
             dlm.addElement(priceList.get(i)); // add elements
         }
             priceOfRoomsjList.setModel(dlm);  // set model for jlist
    
             int numofrooms=clickButton.size();
             String numRooms=String.valueOf(numofrooms);
             numOfRoomTF.setText(numRooms);
             
             setTotalLabel(dlm);
    }//GEN-LAST:event_Fi01jButtonMouseReleased

    private void Fi02jButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Fi02jButtonMouseReleased
        Fi02jButton.setBackground(Color.blue);
          clickButton.add("Fi02");
        int roomNr=27;
        
      // List<String> priceList = new ArrayList<String>();
            
        try {
            priceList.add(roomConnection.searchRoomID(roomNr).getRoomPrice());
        } catch (SQLException ex) {
            Logger.getLogger(FirstFloorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        dlm.clear();
      
        for(int i = 0; i < priceList.size(); i++) {
            
             dlm.addElement(priceList.get(i)); // add elements
         }
             priceOfRoomsjList.setModel(dlm);  // set model for jlist
    
             int numofrooms=clickButton.size();
             String numRooms=String.valueOf(numofrooms);
             numOfRoomTF.setText(numRooms);
             
             setTotalLabel(dlm);
    }//GEN-LAST:event_Fi02jButtonMouseReleased

    private void Fi03jButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Fi03jButtonMouseReleased
        Fi03jButton.setBackground(Color.blue);
          clickButton.add("Fi03");
        int roomNr=28;
        
      // List<String> priceList = new ArrayList<String>();
            
        try {
            priceList.add(roomConnection.searchRoomID(roomNr).getRoomPrice());
        } catch (SQLException ex) {
            Logger.getLogger(FirstFloorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        dlm.clear();
      
        for(int i = 0; i < priceList.size(); i++) {
            
             dlm.addElement(priceList.get(i)); // add elements
         }
             priceOfRoomsjList.setModel(dlm);  // set model for jlist
    
             int numofrooms=clickButton.size();
             String numRooms=String.valueOf(numofrooms);
             numOfRoomTF.setText(numRooms);
             
             setTotalLabel(dlm);
    }//GEN-LAST:event_Fi03jButtonMouseReleased

    private void Fi04jButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Fi04jButtonMouseReleased
        Fi04jButton.setBackground(Color.blue);
          clickButton.add("Fi04");
        int roomNr=29;
        
      // List<String> priceList = new ArrayList<String>();
            
        try {
            priceList.add(roomConnection.searchRoomID(roomNr).getRoomPrice());
        } catch (SQLException ex) {
            Logger.getLogger(FirstFloorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        dlm.clear();
      
        for(int i = 0; i < priceList.size(); i++) {
            
             dlm.addElement(priceList.get(i)); // add elements
         }
             priceOfRoomsjList.setModel(dlm);  // set model for jlist
    
             int numofrooms=clickButton.size();
             String numRooms=String.valueOf(numofrooms);
             numOfRoomTF.setText(numRooms);
             
             setTotalLabel(dlm);
    }//GEN-LAST:event_Fi04jButtonMouseReleased

    private void Fi05jButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Fi05jButtonMouseReleased
        Fi05jButton.setBackground(Color.blue);
          clickButton.add("Fi05");
        int roomNr=30;
        
      // List<String> priceList = new ArrayList<String>();
            
        try {
            priceList.add(roomConnection.searchRoomID(roomNr).getRoomPrice());
        } catch (SQLException ex) {
            Logger.getLogger(FirstFloorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        dlm.clear();
      
        for(int i = 0; i < priceList.size(); i++) {
            
             dlm.addElement(priceList.get(i)); // add elements
         }
             priceOfRoomsjList.setModel(dlm);  // set model for jlist
    
             int numofrooms=clickButton.size();
             String numRooms=String.valueOf(numofrooms);
             numOfRoomTF.setText(numRooms);
             
             setTotalLabel(dlm);
    }//GEN-LAST:event_Fi05jButtonMouseReleased

    private void Fi06jButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Fi06jButtonMouseReleased
        Fi06jButton.setBackground(Color.blue);
          clickButton.add("Fi06");
        int roomNr=31;
        
      // List<String> priceList = new ArrayList<String>();
            
        try {
            priceList.add(roomConnection.searchRoomID(roomNr).getRoomPrice());
        } catch (SQLException ex) {
            Logger.getLogger(FirstFloorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        dlm.clear();
      
        for(int i = 0; i < priceList.size(); i++) {
            
             dlm.addElement(priceList.get(i)); // add elements
         }
             priceOfRoomsjList.setModel(dlm);  // set model for jlist
    
             int numofrooms=clickButton.size();
             String numRooms=String.valueOf(numofrooms);
             numOfRoomTF.setText(numRooms);
             
             setTotalLabel(dlm);
    }//GEN-LAST:event_Fi06jButtonMouseReleased

    private void cancelButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseReleased
        FifthFloorGUI fifthfloor = new FifthFloorGUI(gui);
            gui.jPanel2Main.removeAll();
            gui.jPanel2Main.add(fifthfloor);
            gui.setVisible(true);
            clickButton.clear();
    }//GEN-LAST:event_cancelButtonMouseReleased
public void setTotalLabel(ListModel<Integer> priceSumList) {
        int totalPriceSum = 0;
        
        for (int i = 0; i < priceSumList.getSize(); i++) {
            totalPriceSum += priceSumList.getElementAt(i);
        }
        
        totalTF.setText(totalPriceSum + "");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Fi01jButton;
    private javax.swing.JButton Fi02jButton;
    private javax.swing.JButton Fi03jButton;
    private javax.swing.JButton Fi04jButton;
    private javax.swing.JButton Fi05jButton;
    private javax.swing.JButton Fi06jButton;
    private javax.swing.JButton backButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField customerIDTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField numOfRoomTF;
    private javax.swing.JButton okButton5;
    private javax.swing.JList priceOfRoomsjList;
    private javax.swing.JTextField totalTF;
    // End of variables declaration//GEN-END:variables
}
