package View;

import Database.CustomerConnection;
import Database.ReservationConnection;
import Database.RoomConnection;
import Models.Customer;
import Models.Reservation;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;


/**
 *
 * @author Charlie
 */
public class FirstFloorGUI extends javax.swing.JPanel {
    DefaultListModel dlm=new DefaultListModel();
    private static ArrayList<String> clickButton=new ArrayList<String>();
    List<Integer> priceList = new ArrayList<Integer>();
    RoomConnection roomConnection = new RoomConnection();
    ArrayList<String> roomlist=new ArrayList<String>();
    ArrayList<String> pricelist=new ArrayList<String>();
    CustomerConnection customerconnection = new CustomerConnection();
    ReservationConnection reservationconnection = new ReservationConnection();
    GUI gui;
    
    /**
     * Creates new form FirstFloorGUI
     */
    public FirstFloorGUI(GUI gui) {
        initComponents();
        this.gui=gui;
       customerIDTF.setText(String.valueOf(customerconnection.getNewestCustomerID()));
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        F01jButton = new javax.swing.JButton();
        F02jButton = new javax.swing.JButton();
        F07jButton = new javax.swing.JButton();
        F03jButton = new javax.swing.JButton();
        F04jButton = new javax.swing.JButton();
        F05jButton = new javax.swing.JButton();
        F06jButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        priceOfRoomsjList = new javax.swing.JList();
        numOfRoomTF = new javax.swing.JTextField();
        totalTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        customerIDTF = new javax.swing.JTextField();

        F01jButton.setText("F01");
        F01jButton.setToolTipText("Room for 2 persons");
        F01jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                F01jButtonMouseReleased(evt);
            }
        });

        F02jButton.setText("F02");
        F02jButton.setToolTipText("Room for 2 persons");
        F02jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                F02jButtonMouseReleased(evt);
            }
        });

        F07jButton.setText("F07");
        F07jButton.setToolTipText("Family room");
        F07jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                F07jButtonMouseReleased(evt);
            }
        });

        F03jButton.setText("F03");
        F03jButton.setToolTipText("Luxus Room for 1 person");
        F03jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                F03jButtonMouseReleased(evt);
            }
        });

        F04jButton.setText("F04");
        F04jButton.setToolTipText("Room for 2 person");
        F04jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                F04jButtonMouseReleased(evt);
            }
        });

        F05jButton.setText("F05");
        F05jButton.setToolTipText("Luxus Room for 1 person");
        F05jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                F05jButtonMouseReleased(evt);
            }
        });

        F06jButton.setText("F06");
        F06jButton.setToolTipText("Normal Room for 1 Person");
        F06jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                F06jButtonMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(F02jButton, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(F01jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(F07jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(F05jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(F06jButton, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(F03jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(F04jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(F04jButton, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(F03jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(F05jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(F06jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(F07jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(F02jButton, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(F01jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        backButton.setText("Back");
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                backButtonMouseReleased(evt);
            }
        });

        okButton.setText("OK");
        okButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                okButtonMouseReleased(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cancelButtonMouseReleased(evt);
            }
        });

        jScrollPane1.setViewportView(priceOfRoomsjList);

        jLabel1.setText("Price for each room :");

        jLabel2.setText("Number of rooms :");

        jLabel3.setText("Total :");

        jLabel4.setText("customerID :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(258, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(numOfRoomTF, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(customerIDTF, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(totalTF, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(93, 93, 93)
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(cancelButton)
                        .addGap(30, 30, 30)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(165, 165, 165))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(okButton)
                            .addComponent(backButton)
                            .addComponent(cancelButton))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(customerIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numOfRoomTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(16, 16, 16))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseReleased
          AvailableRoomsGUI availableRooms=new AvailableRoomsGUI(gui);
  
   
            gui.jPanel2Main.removeAll();
            gui.jPanel2Main.repaint();
            gui.jPanel2Main.add(availableRooms);
            gui.jPanel2Main.repaint();
            gui.setVisible(true);
           
           clickButton.clear();
    }//GEN-LAST:event_backButtonMouseReleased

    private void okButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okButtonMouseReleased
    
        int fn = Integer.parseInt(customerIDTF.getText());
        int num = Integer.parseInt(numOfRoomTF.getText());
        int total = Integer.parseInt(totalTF.getText());
        
        
        Reservation reservation = new Reservation(fn,num,total);
        try {
            reservationconnection.createReservation(reservation);
        } catch (SQLException ex) {
            Logger.getLogger(FirstFloorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
            AvailableRoomsGUI availableRooms=new AvailableRoomsGUI(gui);
            
            gui.jPanel2Main.removeAll();
            gui.jPanel2Main.add(availableRooms);
            gui.jPanel2Main.repaint();
            gui.setVisible(true);
  
    }//GEN-LAST:event_okButtonMouseReleased

    private void cancelButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseReleased
        FirstFloorGUI firstfloor = new FirstFloorGUI(gui);
            gui.jPanel2Main.removeAll();
            gui.jPanel2Main.add(firstfloor);
            gui.setVisible(true);
            
            clickButton.clear();
    }//GEN-LAST:event_cancelButtonMouseReleased

    private void F02jButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_F02jButtonMouseReleased
        F02jButton.setBackground(Color.red);
        clickButton.add("F02");
        int roomNr=2;
        
      // List<String> priceList = new ArrayList<String>();
            
        try {
            priceList.add(roomConnection.searchRoomID(roomNr).getRoomPrice());
        } catch (SQLException ex) {
            Logger.getLogger(FirstFloorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        dlm.clear();
      
        for(int i = 0; i < priceList.size(); i++) {
            
             dlm.addElement(priceList.get(i)); // add elements
         }
             priceOfRoomsjList.setModel(dlm);  // set model for jlist
    
             int numofrooms=clickButton.size();
             String numRooms=String.valueOf(numofrooms);
             numOfRoomTF.setText(numRooms);
             
             setTotalLabel(dlm);
             
          
    }//GEN-LAST:event_F02jButtonMouseReleased

    private void F03jButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_F03jButtonMouseReleased
        F03jButton.setBackground(Color.red);
        clickButton.add("F03");
        int roomNr=3;
        
       // List<String> priceList = new ArrayList<String>();
            
        try {
            priceList.add(roomConnection.searchRoomID(roomNr).getRoomPrice());
        } catch (SQLException ex) {
            Logger.getLogger(FirstFloorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        dlm.clear();
      
        for(int i = 0; i < priceList.size(); i++) {
            
             dlm.addElement(priceList.get(i)); // add elements
         }
             priceOfRoomsjList.setModel(dlm);  // set model for jlist
    
             int numofrooms=clickButton.size();
             String numRooms=String.valueOf(numofrooms);
             numOfRoomTF.setText(numRooms);
             
             setTotalLabel(dlm);
    }//GEN-LAST:event_F03jButtonMouseReleased

    private void F04jButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_F04jButtonMouseReleased
        F04jButton.setBackground(Color.red);
        clickButton.add("F04");
        int roomNr=4;
        
       // List<String> priceList = new ArrayList<String>();
            
        try {
            priceList.add(roomConnection.searchRoomID(roomNr).getRoomPrice());
        } catch (SQLException ex) {
            Logger.getLogger(FirstFloorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        dlm.clear();
      
        for(int i = 0; i < priceList.size(); i++) {
            
             dlm.addElement(priceList.get(i)); // add elements
         }
             priceOfRoomsjList.setModel(dlm);  // set model for jlist
    
             int numofrooms=clickButton.size();
             String numRooms=String.valueOf(numofrooms);
             numOfRoomTF.setText(numRooms);
             
             setTotalLabel(dlm);
    }//GEN-LAST:event_F04jButtonMouseReleased

    private void F05jButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_F05jButtonMouseReleased
        F05jButton.setBackground(Color.red);
        clickButton.add("F05");
        int roomNr=5;
        
       // List<String> priceList = new ArrayList<String>();
            
        try {
            priceList.add(roomConnection.searchRoomID(roomNr).getRoomPrice());
        } catch (SQLException ex) {
            Logger.getLogger(FirstFloorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        dlm.clear();
      
        for(int i = 0; i < priceList.size(); i++) {
            
             dlm.addElement(priceList.get(i)); // add elements
         }
             priceOfRoomsjList.setModel(dlm);  // set model for jlist
    
             int numofrooms=clickButton.size();
             String numRooms=String.valueOf(numofrooms);
             numOfRoomTF.setText(numRooms);
             
             setTotalLabel(dlm);
    }//GEN-LAST:event_F05jButtonMouseReleased

    private void F06jButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_F06jButtonMouseReleased
        F06jButton.setBackground(Color.red);
        clickButton.add("F06");
        int roomNr=6;
        
       // List<String> priceList = new ArrayList<String>();
            
        try {
            priceList.add(roomConnection.searchRoomID(roomNr).getRoomPrice());
        } catch (SQLException ex) {
            Logger.getLogger(FirstFloorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        dlm.clear();
      
        for(int i = 0; i < priceList.size(); i++) {
            
             dlm.addElement(priceList.get(i)); // add elements
         }
             priceOfRoomsjList.setModel(dlm);  // set model for jlist
    
             int numofrooms=clickButton.size();
             String numRooms=String.valueOf(numofrooms);
             numOfRoomTF.setText(numRooms);
             
             setTotalLabel(dlm);
    }//GEN-LAST:event_F06jButtonMouseReleased

    private void F07jButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_F07jButtonMouseReleased
        F07jButton.setBackground(Color.red);
        clickButton.add("F07");
        int roomNr=7;
        
       // List<String> priceList = new ArrayList<String>();
            
        try {
            priceList.add(roomConnection.searchRoomID(roomNr).getRoomPrice());
        } catch (SQLException ex) {
            Logger.getLogger(FirstFloorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        dlm.clear();
      
        for(int i = 0; i < priceList.size(); i++) {
            
             dlm.addElement(priceList.get(i)); // add elements
         }
             priceOfRoomsjList.setModel(dlm);  // set model for jlist
    
             int numofrooms=clickButton.size();
             String numRooms=String.valueOf(numofrooms);
             numOfRoomTF.setText(numRooms);
             
             setTotalLabel(dlm);
    }//GEN-LAST:event_F07jButtonMouseReleased

    private void F01jButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_F01jButtonMouseReleased
        F01jButton.setBackground(Color.red);
        clickButton.add("F01");   
        int roomNr=1;
        
        //List<String> priceList = new ArrayList<String>();
            
        try {
            priceList.add(roomConnection.searchRoomID(roomNr).getRoomPrice());
        } catch (SQLException ex) {
            Logger.getLogger(FirstFloorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        dlm.clear();
      
        for(int i = 0; i < priceList.size(); i++) {
            
             dlm.addElement(priceList.get(i)); // add elements
         }
             priceOfRoomsjList.setModel(dlm);  // set model for jlist
    
             int numofrooms=clickButton.size();
             String numRooms=String.valueOf(numofrooms);
             numOfRoomTF.setText(numRooms);
             
             
             setTotalLabel(dlm);
    }//GEN-LAST:event_F01jButtonMouseReleased
public void setTotalLabel(ListModel<Integer> priceSumList) {
        int totalPriceSum = 0;
        
        for (int i = 0; i < priceSumList.getSize(); i++) {
            totalPriceSum += priceSumList.getElementAt(i);
        }
        
        totalTF.setText(totalPriceSum+"");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton F01jButton;
    private javax.swing.JButton F02jButton;
    private javax.swing.JButton F03jButton;
    private javax.swing.JButton F04jButton;
    private javax.swing.JButton F05jButton;
    private javax.swing.JButton F06jButton;
    private javax.swing.JButton F07jButton;
    private javax.swing.JButton backButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField customerIDTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField numOfRoomTF;
    private javax.swing.JButton okButton;
    private javax.swing.JList priceOfRoomsjList;
    private javax.swing.JTextField totalTF;
    // End of variables declaration//GEN-END:variables
}
