package View;

import Database.CustomerConnection;
import Database.ReservationConnection;
import Database.RoomConnection;
import Models.Reservation;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;

/**
 *
 * @author Charlie
 */
public class FourthFloorGUI extends javax.swing.JPanel {
    DefaultListModel dlm=new DefaultListModel();
    private static ArrayList<String> clickButton=new ArrayList<String>();
    List<Integer> priceList = new ArrayList<Integer>();
    RoomConnection roomConnection = new RoomConnection();
    CustomerConnection customerconnection = new CustomerConnection();
    ReservationConnection reservationconnection = new ReservationConnection();
    GUI gui;
    /**
     * Creates new form FourthFloorGUI
     */
    public FourthFloorGUI(GUI gui) {
        initComponents();
        this.gui=gui;
        customerIDTF.setText(String.valueOf(customerconnection.getNewestCustomerID()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Fo01jButton = new javax.swing.JButton();
        Fo02jButton = new javax.swing.JButton();
        Fo03jButton = new javax.swing.JButton();
        Fo04jButton = new javax.swing.JButton();
        Fo05jButton = new javax.swing.JButton();
        Fo06jButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        okButton4 = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        priceOfRoomsjList = new javax.swing.JList();
        numOfRoomTF = new javax.swing.JTextField();
        totalTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        customerIDTF = new javax.swing.JTextField();

        Fo01jButton.setText("Fou1");
        Fo01jButton.setToolTipText("Room for 2 Persons");
        Fo01jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Fo01jButtonMouseReleased(evt);
            }
        });

        Fo02jButton.setText("Fou2");
        Fo02jButton.setToolTipText("Room for 1 Person");
        Fo02jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Fo02jButtonMouseReleased(evt);
            }
        });

        Fo03jButton.setText("Fou3");
        Fo03jButton.setToolTipText("Luxus Room for 2 Persons");
        Fo03jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Fo03jButtonMouseReleased(evt);
            }
        });

        Fo04jButton.setText("Fou4");
        Fo04jButton.setToolTipText("Room for 2 Persons");
        Fo04jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Fo04jButtonMouseReleased(evt);
            }
        });

        Fo05jButton.setText("Fou5");
        Fo05jButton.setToolTipText("Room for 1 Person");
        Fo05jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Fo05jButtonMouseReleased(evt);
            }
        });

        Fo06jButton.setText("Fou6");
        Fo06jButton.setToolTipText("Family Room");
        Fo06jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Fo06jButtonMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Fo02jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Fo01jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Fo03jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(Fo06jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Fo04jButton, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addComponent(Fo05jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Fo04jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Fo02jButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Fo03jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 105, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Fo01jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Fo06jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Fo05jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        backButton.setText("Back");
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                backButtonMouseReleased(evt);
            }
        });

        okButton4.setText("OK");
        okButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                okButton4MouseReleased(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cancelButtonMouseReleased(evt);
            }
        });

        jScrollPane1.setViewportView(priceOfRoomsjList);

        jLabel1.setText("Price for each room :");

        jLabel2.setText("Number of rooms :");

        jLabel3.setText("Total :");

        jLabel4.setText("CustomerID : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(okButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(112, 112, 112))
            .addGroup(layout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numOfRoomTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(customerIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(totalTF, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(485, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(backButton)
                            .addComponent(okButton4)
                            .addComponent(cancelButton)
                            .addComponent(customerIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numOfRoomTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseReleased
         AvailableRoomsGUI availableRooms=new AvailableRoomsGUI(gui);
  
            
            gui.jPanel2Main.removeAll();
            gui.jPanel2Main.repaint();
            gui.jPanel2Main.add(availableRooms);
            gui.jPanel2Main.repaint();
            gui.setVisible(true);
            clickButton.clear();
    }//GEN-LAST:event_backButtonMouseReleased

    private void okButton4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okButton4MouseReleased
        int fn = Integer.parseInt(customerIDTF.getText());
        int num = Integer.parseInt(numOfRoomTF.getText());
        int total = Integer.parseInt(totalTF.getText());
        
        
        Reservation reservation = new Reservation(fn,num,total);
        try {
            reservationconnection.createReservation(reservation);
        } catch (SQLException ex) {
            Logger.getLogger(FirstFloorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
            AvailableRoomsGUI availableRooms=new AvailableRoomsGUI(gui);
            
            gui.jPanel2Main.removeAll();
            gui.jPanel2Main.add(availableRooms);
            gui.jPanel2Main.repaint();
            gui.setVisible(true);
    }//GEN-LAST:event_okButton4MouseReleased

    private void Fo01jButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Fo01jButtonMouseReleased
        Fo01jButton.setBackground(Color.CYAN);
        clickButton.add("Fo01");
        int roomNr=20;
        
      // List<String> priceList = new ArrayList<String>();
            
        try {
            priceList.add(roomConnection.searchRoomID(roomNr).getRoomPrice());
        } catch (SQLException ex) {
            Logger.getLogger(FirstFloorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        dlm.clear();
      
        for(int i = 0; i < priceList.size(); i++) {
            
             dlm.addElement(priceList.get(i)); // add elements
         }
             priceOfRoomsjList.setModel(dlm);  // set model for jlist
    
             int numofrooms=clickButton.size();
             String numRooms=String.valueOf(numofrooms);
             numOfRoomTF.setText(numRooms);
             
             setTotalLabel(dlm);
    }//GEN-LAST:event_Fo01jButtonMouseReleased

    private void Fo02jButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Fo02jButtonMouseReleased
        Fo02jButton.setBackground(Color.CYAN);
          clickButton.add("Fo02");
        int roomNr=21;
        
      // List<String> priceList = new ArrayList<String>();
            
        try {
            priceList.add(roomConnection.searchRoomID(roomNr).getRoomPrice());
        } catch (SQLException ex) {
            Logger.getLogger(FirstFloorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        dlm.clear();
      
        for(int i = 0; i < priceList.size(); i++) {
            
             dlm.addElement(priceList.get(i)); // add elements
         }
             priceOfRoomsjList.setModel(dlm);  // set model for jlist
    
             int numofrooms=clickButton.size();
             String numRooms=String.valueOf(numofrooms);
             numOfRoomTF.setText(numRooms);
             
             setTotalLabel(dlm);
    }//GEN-LAST:event_Fo02jButtonMouseReleased

    private void Fo03jButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Fo03jButtonMouseReleased
        Fo03jButton.setBackground(Color.CYAN);
          clickButton.add("Fo03");
        int roomNr=22;
        
      // List<String> priceList = new ArrayList<String>();
            
        try {
            priceList.add(roomConnection.searchRoomID(roomNr).getRoomPrice());
        } catch (SQLException ex) {
            Logger.getLogger(FirstFloorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        dlm.clear();
      
        for(int i = 0; i < priceList.size(); i++) {
            
             dlm.addElement(priceList.get(i)); // add elements
         }
             priceOfRoomsjList.setModel(dlm);  // set model for jlist
    
             int numofrooms=clickButton.size();
             String numRooms=String.valueOf(numofrooms);
             numOfRoomTF.setText(numRooms);
             
             setTotalLabel(dlm);
    }//GEN-LAST:event_Fo03jButtonMouseReleased

    private void Fo04jButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Fo04jButtonMouseReleased
        Fo04jButton.setBackground(Color.CYAN);
          clickButton.add("Fo04");
        int roomNr=23;
        
      // List<String> priceList = new ArrayList<String>();
            
        try {
            priceList.add(roomConnection.searchRoomID(roomNr).getRoomPrice());
        } catch (SQLException ex) {
            Logger.getLogger(FirstFloorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        dlm.clear();
      
        for(int i = 0; i < priceList.size(); i++) {
            
             dlm.addElement(priceList.get(i)); // add elements
         }
             priceOfRoomsjList.setModel(dlm);  // set model for jlist
    
             int numofrooms=clickButton.size();
             String numRooms=String.valueOf(numofrooms);
             numOfRoomTF.setText(numRooms);
             
             setTotalLabel(dlm);
    }//GEN-LAST:event_Fo04jButtonMouseReleased

    private void Fo05jButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Fo05jButtonMouseReleased
        Fo05jButton.setBackground(Color.CYAN);
          clickButton.add("Fo05");
        int roomNr=24;
        
      // List<String> priceList = new ArrayList<String>();
            
        try {
            priceList.add(roomConnection.searchRoomID(roomNr).getRoomPrice());
        } catch (SQLException ex) {
            Logger.getLogger(FirstFloorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        dlm.clear();
      
        for(int i = 0; i < priceList.size(); i++) {
            
             dlm.addElement(priceList.get(i)); // add elements
         }
             priceOfRoomsjList.setModel(dlm);  // set model for jlist
    
             int numofrooms=clickButton.size();
             String numRooms=String.valueOf(numofrooms);
             numOfRoomTF.setText(numRooms);
             
             setTotalLabel(dlm);
    }//GEN-LAST:event_Fo05jButtonMouseReleased

    private void Fo06jButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Fo06jButtonMouseReleased
        Fo06jButton.setBackground(Color.CYAN);
        clickButton.add("Fo06");
        int roomNr=25;
        
      // List<String> priceList = new ArrayList<String>();
            
        try {
            priceList.add(roomConnection.searchRoomID(roomNr).getRoomPrice());
        } catch (SQLException ex) {
            Logger.getLogger(FirstFloorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        dlm.clear();
      
        for(int i = 0; i < priceList.size(); i++) {
            
             dlm.addElement(priceList.get(i)); // add elements
         }
             priceOfRoomsjList.setModel(dlm);  // set model for jlist
    
             int numofrooms=clickButton.size();
             String numRooms=String.valueOf(numofrooms);
             numOfRoomTF.setText(numRooms);
             
             setTotalLabel(dlm);
    }//GEN-LAST:event_Fo06jButtonMouseReleased

    private void cancelButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseReleased
         FourthFloorGUI fourthfloor = new FourthFloorGUI(gui);
            gui.jPanel2Main.removeAll();
            gui.jPanel2Main.add(fourthfloor);
            gui.setVisible(true);
            clickButton.clear();
    }//GEN-LAST:event_cancelButtonMouseReleased
public void setTotalLabel(ListModel<Integer> priceSumList) {
        int totalPriceSum = 0;
        
        for (int i = 0; i < priceSumList.getSize(); i++) {
            totalPriceSum += priceSumList.getElementAt(i);
        }
        
        totalTF.setText(totalPriceSum + "");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Fo01jButton;
    private javax.swing.JButton Fo02jButton;
    private javax.swing.JButton Fo03jButton;
    private javax.swing.JButton Fo04jButton;
    private javax.swing.JButton Fo05jButton;
    private javax.swing.JButton Fo06jButton;
    private javax.swing.JButton backButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField customerIDTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField numOfRoomTF;
    private javax.swing.JButton okButton4;
    private javax.swing.JList priceOfRoomsjList;
    private javax.swing.JTextField totalTF;
    // End of variables declaration//GEN-END:variables
}
