package View;

import Database.CustomerConnection;
import Database.ReservationConnection;
import Database.RoomConnection;
import Models.Reservation;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;

/**
 *
 * @author Charlie
 */
public class SecondFloorGUI extends javax.swing.JPanel {
    DefaultListModel dlm=new DefaultListModel();
    private static ArrayList<String> clickButton=new ArrayList<String>();
    List<Integer> priceList = new ArrayList<Integer>();
    RoomConnection roomConnection = new RoomConnection();
    CustomerConnection customerconnection = new CustomerConnection();
    ReservationConnection reservationconnection = new ReservationConnection();
    GUI gui;
    /**
     * Creates new form SecondFloorGUI
     */
    public SecondFloorGUI(GUI gui) {
        initComponents();
        this.gui=gui;
        customerIDTF.setText(String.valueOf(customerconnection.getNewestCustomerID()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        S01jButton = new javax.swing.JButton();
        S02jButton = new javax.swing.JButton();
        S03jButton = new javax.swing.JButton();
        S04jButton = new javax.swing.JButton();
        S05jButton = new javax.swing.JButton();
        S06jButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        okButton2 = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        priceOfRoomsjList = new javax.swing.JList();
        numOfRoomTF = new javax.swing.JTextField();
        totalTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        customerIDTF = new javax.swing.JTextField();

        S01jButton.setText("S01");
        S01jButton.setToolTipText("Room for 2 persons");
        S01jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                S01jButtonMouseReleased(evt);
            }
        });

        S02jButton.setText("S02");
        S02jButton.setToolTipText("Room for 1 person");
        S02jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                S02jButtonMouseReleased(evt);
            }
        });

        S03jButton.setText("S03");
        S03jButton.setToolTipText("Room for 2 persons");
        S03jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                S03jButtonMouseReleased(evt);
            }
        });

        S04jButton.setText("S04");
        S04jButton.setToolTipText("Room for 1 person");
        S04jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                S04jButtonMouseReleased(evt);
            }
        });

        S05jButton.setText("S05");
        S05jButton.setToolTipText("Room for 2 persons");
        S05jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                S05jButtonMouseReleased(evt);
            }
        });

        S06jButton.setText("S06");
        S06jButton.setToolTipText("Family Room");
        S06jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                S06jButtonMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(S02jButton, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                    .addComponent(S01jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(S03jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(S06jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(S04jButton, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(S05jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(S04jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(S02jButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(S03jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 94, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(S05jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(S01jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(S06jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        backButton.setText("Back");
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                backButtonMouseReleased(evt);
            }
        });

        okButton2.setText("OK");
        okButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                okButton2MouseReleased(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cancelButtonMouseReleased(evt);
            }
        });

        jScrollPane1.setViewportView(priceOfRoomsjList);

        jLabel1.setText("Price for each room :");

        jLabel2.setText("Number of rooms :");

        jLabel3.setText("Total :");

        jLabel4.setText("CustomerID : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(199, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numOfRoomTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(customerIDTF, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(totalTF, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(59, 59, 59)
                        .addComponent(okButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelButton)
                        .addGap(10, 10, 10)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(112, 112, 112))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(customerIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numOfRoomTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(okButton2)
                    .addComponent(cancelButton))
                .addGap(172, 172, 172))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseReleased
         AvailableRoomsGUI availableRooms=new AvailableRoomsGUI(gui);
  
            
            gui.jPanel2Main.removeAll();
            gui.jPanel2Main.repaint();
            gui.jPanel2Main.add(availableRooms);
            gui.jPanel2Main.repaint();
            gui.setVisible(true);
            clickButton.clear();
    }//GEN-LAST:event_backButtonMouseReleased

    private void okButton2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okButton2MouseReleased
        int fn = Integer.parseInt(customerIDTF.getText());
        int num = Integer.parseInt(numOfRoomTF.getText());
        int total = Integer.parseInt(totalTF.getText());
        
        
        Reservation reservation = new Reservation(fn,num,total);
        try {
            reservationconnection.createReservation(reservation);
        } catch (SQLException ex) {
            Logger.getLogger(FirstFloorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
            AvailableRoomsGUI availableRooms=new AvailableRoomsGUI(gui);
            
            gui.jPanel2Main.removeAll();
            gui.jPanel2Main.add(availableRooms);
            gui.jPanel2Main.repaint();
            gui.setVisible(true);
    }//GEN-LAST:event_okButton2MouseReleased

    private void S01jButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S01jButtonMouseReleased
        S01jButton.setBackground(Color.ORANGE);
        clickButton.add("S01");
        int roomNr=8;
        
      // List<String> priceList = new ArrayList<String>();
            
        try {
            priceList.add(roomConnection.searchRoomID(roomNr).getRoomPrice());
        } catch (SQLException ex) {
            Logger.getLogger(FirstFloorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        dlm.clear();
      
        for(int i = 0; i < priceList.size(); i++) {
            
             dlm.addElement(priceList.get(i)); // add elements
         }
             priceOfRoomsjList.setModel(dlm);  // set model for jlist
    
             int numofrooms=clickButton.size();
             String numRooms=String.valueOf(numofrooms);
             numOfRoomTF.setText(numRooms);
             
             setTotalLabel(dlm);
        
        
    }//GEN-LAST:event_S01jButtonMouseReleased

    private void S02jButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S02jButtonMouseReleased
        S02jButton.setBackground(Color.ORANGE);
        clickButton.add("S02");
        int roomNr=9;
        
      // List<String> priceList = new ArrayList<String>();
            
        try {
            priceList.add(roomConnection.searchRoomID(roomNr).getRoomPrice());
        } catch (SQLException ex) {
            Logger.getLogger(FirstFloorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        dlm.clear();
      
        for(int i = 0; i < priceList.size(); i++) {
            
             dlm.addElement(priceList.get(i)); // add elements
         }
             priceOfRoomsjList.setModel(dlm);  // set model for jlist
    
             int numofrooms=clickButton.size();
             String numRooms=String.valueOf(numofrooms);
             numOfRoomTF.setText(numRooms);
             
             setTotalLabel(dlm);
        
    }//GEN-LAST:event_S02jButtonMouseReleased

    private void S03jButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S03jButtonMouseReleased
        S03jButton.setBackground(Color.ORANGE);
        clickButton.add("S03");
        int roomNr=10;
        
      // List<String> priceList = new ArrayList<String>();
            
        try {
            priceList.add(roomConnection.searchRoomID(roomNr).getRoomPrice());
        } catch (SQLException ex) {
            Logger.getLogger(FirstFloorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        dlm.clear();
      
        for(int i = 0; i < priceList.size(); i++) {
            
             dlm.addElement(priceList.get(i)); // add elements
         }
             priceOfRoomsjList.setModel(dlm);  // set model for jlist
    
             int numofrooms=clickButton.size();
             String numRooms=String.valueOf(numofrooms);
             numOfRoomTF.setText(numRooms);
             
             setTotalLabel(dlm);
    }//GEN-LAST:event_S03jButtonMouseReleased

    private void S04jButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S04jButtonMouseReleased
        S04jButton.setBackground(Color.ORANGE);
        clickButton.add("S04");
        int roomNr=11;
        
      // List<String> priceList = new ArrayList<String>();
            
        try {
            priceList.add(roomConnection.searchRoomID(roomNr).getRoomPrice());
        } catch (SQLException ex) {
            Logger.getLogger(FirstFloorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        dlm.clear();
      
        for(int i = 0; i < priceList.size(); i++) {
            
             dlm.addElement(priceList.get(i)); // add elements
         }
             priceOfRoomsjList.setModel(dlm);  // set model for jlist
    
             int numofrooms=clickButton.size();
             String numRooms=String.valueOf(numofrooms);
             numOfRoomTF.setText(numRooms);
             
             setTotalLabel(dlm);
    }//GEN-LAST:event_S04jButtonMouseReleased

    private void S05jButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S05jButtonMouseReleased
        S05jButton.setBackground(Color.ORANGE);
        clickButton.add("S05");
        int roomNr=12;
        
      // List<String> priceList = new ArrayList<String>();
            
        try {
            priceList.add(roomConnection.searchRoomID(roomNr).getRoomPrice());
        } catch (SQLException ex) {
            Logger.getLogger(FirstFloorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        dlm.clear();
      
        for(int i = 0; i < priceList.size(); i++) {
            
             dlm.addElement(priceList.get(i)); // add elements
         }
             priceOfRoomsjList.setModel(dlm);  // set model for jlist
    
             int numofrooms=clickButton.size();
             String numRooms=String.valueOf(numofrooms);
             numOfRoomTF.setText(numRooms);
             
             setTotalLabel(dlm);
    }//GEN-LAST:event_S05jButtonMouseReleased

    private void S06jButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S06jButtonMouseReleased
        S06jButton.setBackground(Color.ORANGE);
        clickButton.add("S06");
        int roomNr=13;
        
      // List<String> priceList = new ArrayList<String>();
            
        try {
            priceList.add(roomConnection.searchRoomID(roomNr).getRoomPrice());
        } catch (SQLException ex) {
            Logger.getLogger(FirstFloorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        dlm.clear();
      
        for(int i = 0; i < priceList.size(); i++) {
            
             dlm.addElement(priceList.get(i)); // add elements
         }
             priceOfRoomsjList.setModel(dlm);  // set model for jlist
    
             int numofrooms=clickButton.size();
             String numRooms=String.valueOf(numofrooms);
             numOfRoomTF.setText(numRooms);
             
             setTotalLabel(dlm);
    }//GEN-LAST:event_S06jButtonMouseReleased

    private void cancelButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseReleased
        SecondFloorGUI secondfloor = new SecondFloorGUI(gui);
            gui.jPanel2Main.removeAll();
            gui.jPanel2Main.add(secondfloor);
            gui.setVisible(true);
            clickButton.clear();
    }//GEN-LAST:event_cancelButtonMouseReleased
    
    public void setTotalLabel(ListModel<Integer> priceSumList) {
        int totalPriceSum = 0;
        
        for (int i = 0; i < priceSumList.getSize(); i++) {
            totalPriceSum += priceSumList.getElementAt(i);
        }
        
        totalTF.setText(totalPriceSum + "");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton S01jButton;
    private javax.swing.JButton S02jButton;
    private javax.swing.JButton S03jButton;
    private javax.swing.JButton S04jButton;
    private javax.swing.JButton S05jButton;
    private javax.swing.JButton S06jButton;
    private javax.swing.JButton backButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField customerIDTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField numOfRoomTF;
    private javax.swing.JButton okButton2;
    private javax.swing.JList priceOfRoomsjList;
    private javax.swing.JTextField totalTF;
    // End of variables declaration//GEN-END:variables
}
