package View;

import Database.CustomerConnection;
import Database.ReservationConnection;
import Database.RoomConnection;
import Models.Reservation;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;

/**
 *
 * @author Charlie
 */
public class ThirdFloorGUI extends javax.swing.JPanel {
    DefaultListModel dlm=new DefaultListModel();
    private static ArrayList<String> clickButton=new ArrayList<String>();
    List<Integer> priceList = new ArrayList<Integer>();
    RoomConnection roomConnection = new RoomConnection();
    CustomerConnection customerconnection = new CustomerConnection();
    ReservationConnection reservationconnection = new ReservationConnection();
    GUI gui;
    /**
     * Creates new form ThirdFloorGUI
     */
    public ThirdFloorGUI(GUI gui) {
        initComponents();
        this.gui=gui;
        customerIDTF.setText(String.valueOf(customerconnection.getNewestCustomerID()));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        T01jButton = new javax.swing.JButton();
        T02jButton = new javax.swing.JButton();
        T03jButton = new javax.swing.JButton();
        T04jButton = new javax.swing.JButton();
        T05jButton = new javax.swing.JButton();
        T06jButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        okButton3 = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        priceOfRoomsjList = new javax.swing.JList();
        numOfRoomTF = new javax.swing.JTextField();
        totalTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        customerIDTF = new javax.swing.JTextField();

        T01jButton.setText("T01");
        T01jButton.setToolTipText("Room for 2 Persons");
        T01jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                T01jButtonMouseReleased(evt);
            }
        });

        T02jButton.setText("T02");
        T02jButton.setToolTipText("Room for 1 Person");
        T02jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                T02jButtonMouseReleased(evt);
            }
        });

        T03jButton.setText("T03");
        T03jButton.setToolTipText("Luxus Room for 2 Persons");
        T03jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                T03jButtonMouseReleased(evt);
            }
        });

        T04jButton.setText("T04");
        T04jButton.setToolTipText("Room for 2 Persons");
        T04jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                T04jButtonMouseReleased(evt);
            }
        });

        T05jButton.setText("T05");
        T05jButton.setToolTipText("Room for 1 Person");
        T05jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                T05jButtonMouseReleased(evt);
            }
        });

        T06jButton.setText("T06");
        T06jButton.setToolTipText("Family Room");
        T06jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                T06jButtonMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(T02jButton, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(T01jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(T03jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(T06jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(T05jButton, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(T04jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(T04jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(T02jButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(T03jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 98, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(T01jButton, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addComponent(T05jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(T06jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        backButton.setText("Back");
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                backButtonMouseReleased(evt);
            }
        });

        okButton3.setText("OK");
        okButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                okButton3MouseReleased(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cancelButtonMouseReleased(evt);
            }
        });

        jLabel1.setText("Price for each room :");

        jLabel2.setText("Number of rooms :");

        jLabel3.setText("Total :");

        jScrollPane1.setViewportView(priceOfRoomsjList);

        jLabel5.setText("CustomerID : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(228, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numOfRoomTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(customerIDTF, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(totalTF, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(125, 125, 125)
                        .addComponent(okButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(153, 153, 153))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(customerIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(backButton)
                        .addComponent(okButton3)
                        .addComponent(cancelButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numOfRoomTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseReleased
         AvailableRoomsGUI availableRooms=new AvailableRoomsGUI(gui);
  
            
            gui.jPanel2Main.removeAll();
            gui.jPanel2Main.repaint();
            gui.jPanel2Main.add(availableRooms);
            gui.jPanel2Main.repaint();
            gui.setVisible(true);
            clickButton.clear();
    }//GEN-LAST:event_backButtonMouseReleased

    private void okButton3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okButton3MouseReleased
        int fn = Integer.parseInt(customerIDTF.getText());
        int num = Integer.parseInt(numOfRoomTF.getText());
        int total = Integer.parseInt(totalTF.getText());
        
        
        Reservation reservation = new Reservation(fn,num,total);
        try {
            reservationconnection.createReservation(reservation);
        } catch (SQLException ex) {
            Logger.getLogger(FirstFloorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
            AvailableRoomsGUI availableRooms=new AvailableRoomsGUI(gui);
            
            gui.jPanel2Main.removeAll();
            gui.jPanel2Main.add(availableRooms);
            gui.jPanel2Main.repaint();
            gui.setVisible(true);
    }//GEN-LAST:event_okButton3MouseReleased

    private void T01jButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T01jButtonMouseReleased
        T01jButton.setBackground(Color.yellow);
        clickButton.add("T01");
        int roomNr=14;
        
      // List<String> priceList = new ArrayList<String>();
            
        try {
            priceList.add(roomConnection.searchRoomID(roomNr).getRoomPrice());
        } catch (SQLException ex) {
            Logger.getLogger(FirstFloorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        dlm.clear();
      
        for(int i = 0; i < priceList.size(); i++) {
            
             dlm.addElement(priceList.get(i)); // add elements
         }
             priceOfRoomsjList.setModel(dlm);  // set model for jlist
    
             int numofrooms=clickButton.size();
             String numRooms=String.valueOf(numofrooms);
             numOfRoomTF.setText(numRooms);
             
             setTotalLabel(dlm);
    }//GEN-LAST:event_T01jButtonMouseReleased

    private void T02jButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T02jButtonMouseReleased
        T02jButton.setBackground(Color.yellow);
        clickButton.add("T02");
        int roomNr=15;
        
      // List<String> priceList = new ArrayList<String>();
            
        try {
            priceList.add(roomConnection.searchRoomID(roomNr).getRoomPrice());
        } catch (SQLException ex) {
            Logger.getLogger(FirstFloorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        dlm.clear();
      
        for(int i = 0; i < priceList.size(); i++) {
            
             dlm.addElement(priceList.get(i)); // add elements
         }
             priceOfRoomsjList.setModel(dlm);  // set model for jlist
    
             int numofrooms=clickButton.size();
             String numRooms=String.valueOf(numofrooms);
             numOfRoomTF.setText(numRooms);
             
             setTotalLabel(dlm);
    }//GEN-LAST:event_T02jButtonMouseReleased

    private void T03jButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T03jButtonMouseReleased
        T03jButton.setBackground(Color.yellow);
        clickButton.add("T03");
        int roomNr=16;
        
      // List<String> priceList = new ArrayList<String>();
            
        try {
            priceList.add(roomConnection.searchRoomID(roomNr).getRoomPrice());
        } catch (SQLException ex) {
            Logger.getLogger(FirstFloorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        dlm.clear();
      
        for(int i = 0; i < priceList.size(); i++) {
            
             dlm.addElement(priceList.get(i)); // add elements
         }
             priceOfRoomsjList.setModel(dlm);  // set model for jlist
    
             int numofrooms=clickButton.size();
             String numRooms=String.valueOf(numofrooms);
             numOfRoomTF.setText(numRooms);
             
             setTotalLabel(dlm);
    }//GEN-LAST:event_T03jButtonMouseReleased

    private void T04jButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T04jButtonMouseReleased
        T04jButton.setBackground(Color.yellow);
        clickButton.add("T04");
        int roomNr=17;
        
      // List<String> priceList = new ArrayList<String>();
            
        try {
            priceList.add(roomConnection.searchRoomID(roomNr).getRoomPrice());
        } catch (SQLException ex) {
            Logger.getLogger(FirstFloorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        dlm.clear();
      
        for(int i = 0; i < priceList.size(); i++) {
            
             dlm.addElement(priceList.get(i)); // add elements
         }
             priceOfRoomsjList.setModel(dlm);  // set model for jlist
    
             int numofrooms=clickButton.size();
             String numRooms=String.valueOf(numofrooms);
             numOfRoomTF.setText(numRooms);
             
             setTotalLabel(dlm);
    }//GEN-LAST:event_T04jButtonMouseReleased

    private void T05jButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T05jButtonMouseReleased
        T05jButton.setBackground(Color.yellow);
        clickButton.add("T05");
        int roomNr=18;
        
      // List<String> priceList = new ArrayList<String>();
            
        try {
            priceList.add(roomConnection.searchRoomID(roomNr).getRoomPrice());
        } catch (SQLException ex) {
            Logger.getLogger(FirstFloorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        dlm.clear();
      
        for(int i = 0; i < priceList.size(); i++) {
            
             dlm.addElement(priceList.get(i)); // add elements
         }
             priceOfRoomsjList.setModel(dlm);  // set model for jlist
    
             int numofrooms=clickButton.size();
             String numRooms=String.valueOf(numofrooms);
             numOfRoomTF.setText(numRooms);
             
             setTotalLabel(dlm);
    }//GEN-LAST:event_T05jButtonMouseReleased

    private void T06jButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T06jButtonMouseReleased
        T06jButton.setBackground(Color.yellow);
        clickButton.add("T06");
        int roomNr=19;
        
      // List<String> priceList = new ArrayList<String>();
            
        try {
            priceList.add(roomConnection.searchRoomID(roomNr).getRoomPrice());
        } catch (SQLException ex) {
            Logger.getLogger(FirstFloorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        dlm.clear();
      
        for(int i = 0; i < priceList.size(); i++) {
            
             dlm.addElement(priceList.get(i)); // add elements
         }
             priceOfRoomsjList.setModel(dlm);  // set model for jlist
    
             int numofrooms=clickButton.size();
             String numRooms=String.valueOf(numofrooms);
             numOfRoomTF.setText(numRooms);
             
             setTotalLabel(dlm);
    }//GEN-LAST:event_T06jButtonMouseReleased

    private void cancelButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseReleased
         ThirdFloorGUI thirdfloor = new ThirdFloorGUI(gui);
            gui.jPanel2Main.removeAll();
            gui.jPanel2Main.add(thirdfloor);
            gui.setVisible(true);
            clickButton.clear();
    }//GEN-LAST:event_cancelButtonMouseReleased
     public void setTotalLabel(ListModel<Integer> priceSumList) {
        int totalPriceSum = 0;
        
        for (int i = 0; i < priceSumList.getSize(); i++) {
            totalPriceSum += priceSumList.getElementAt(i);
        }
        
        totalTF.setText(totalPriceSum + "");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton T01jButton;
    private javax.swing.JButton T02jButton;
    private javax.swing.JButton T03jButton;
    private javax.swing.JButton T04jButton;
    private javax.swing.JButton T05jButton;
    private javax.swing.JButton T06jButton;
    private javax.swing.JButton backButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField customerIDTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField numOfRoomTF;
    private javax.swing.JButton okButton3;
    private javax.swing.JList priceOfRoomsjList;
    private javax.swing.JTextField totalTF;
    // End of variables declaration//GEN-END:variables
}
